# Generated by Django 4.0.3 on 2022-03-18 09:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(editable=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='The number of the part in the Quran. The maximum is 30.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(editable=False, max_length=14, unique=True, verbose_name='Chapter name in English. The maximum length is 14 as of the current version.')),
                ('name_ar', models.CharField(editable=False, max_length=14, unique=True, verbose_name='Chapter name in Arabic in UthmanicHafs ttf font file with diacritics included. The maximum length is 14 as of the current version.')),
                ('clean_name_ar', models.CharField(editable=False, max_length=14, unique=True, verbose_name='Clean text of the chapter name in Arabic with no diacritics included.')),
                ('number', models.PositiveSmallIntegerField(editable=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(114)], verbose_name='The number of the chapter in the Quran. The maximum is 114 as the last chapter number is 114.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aya',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(editable=False, verbose_name='The actual text of the verse in UthmanicHafs ttf font file with diacritics included.')),
                ('clean_text', models.TextField(editable=False, verbose_name='Clean text of the Aya used for search purpose with no diacritics included.')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(286)], verbose_name='The number of the verse in the chapter. The maximum is 286 as the longest chapter only has 286 verses.')),
                ('page', models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(604)], verbose_name='The page number this verse is in. The maximum is 604.')),
                ('line_start', models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Start line of the verse. The maximum is 15.')),
                ('line_end', models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='End line of the verse. The maximum is 15.')),
                ('juz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quran.juz')),
                ('sora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quran.sora')),
            ],
            options={
                'unique_together': {('sora', 'number')},
            },
        ),
    ]
