# Generated by Django 4.0.3 on 2022-03-22 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_auto_20220317_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aya',
            name='juz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ayas', to='quran.juz'),
        ),
        migrations.AlterField(
            model_name='aya',
            name='sora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ayas', to='quran.sora'),
        ),
    ]
