# Generated by Django 4.0.3 on 2022-03-26 20:21

from django.db import migrations


def change_al_imran_sora_name(apps, schema_editor):
    """
    We need this to fix the browser rendering for Āl-‘Imrān in the browser.
    """
    Sora = apps.get_model("quran", "Sora")
    sora = Sora.objects.get(number=3)
    sora.name_ar = "آلِ عِمۡرَانَ"
    sora.save()


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0003_alter_aya_juz_alter_aya_sora"),
    ]

    operations = [
        migrations.RunPython(change_al_imran_sora_name),
    ]
